### PR TITLE
Tighten up ESM_KEYWORDS

### LINKED ISSUE #295: Non module script incorrectly detected as module
Looks like the [ESM_KEYWORD](https://github.com/preactjs/wmr/blob/2024c9bd8e1ffa7192a37ecea7de53db3695f7e9/src/plugins/fast-cjs-plugin.js#L3) regex isn't specific enough. It matches the following code and thinks that this is a module file:

```js
(function () {
	'use strict';
	// import statements are fun <- this should not be detected as a module file
	window.out.textContent = 'should work';
})();
```

Another snippet that causes the same issue:

```jsx
function foo() {
  // The next line is not an indicator that this is a module file
  return "<div>Add the import to your file</div>"
}
```

The incorrect detection leads to the following error:

```txt
SyntaxError: Cannot use import statement outside a module
```

Workaround: Downgrading to `wmr@0.0.11` works.

### PR DESCRIPTION
**Pull request by developit**
Fixes #295.

### CODE REVIEW

File: src/plugins/fast-cjs-plugin.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 const CJS_KEYWORDS = /\b(module\.exports|exports)\b/;
 
-export const ESM_KEYWORDS = /(\bimport\s*(\{|\s['"\w_$])|[\s;]export(\s+(default|const|var|let)[^\w$]|\s*\{))/;
+export const ESM_KEYWORDS = /(\bimport\s*(\{.*?\}\s*from|\s[\w$]\s+from)?\s*['"]|[\s;]export(\s+(default|const|var|let)[^\w$]|\s*\{))/;
```
Comment (marvinhagemeister) [inline src/plugins/fast-cjs-plugin.js:3]: This doesn't match a default export like:

```js
import foo from "bar";
```

I think your suggestion on slack to experiment with alternative solutions is better for the long term. A regex can always lead to false positives :+1:

Comment (developit) [reply src/plugins/fast-cjs-plugin.js:3]: I didn't suggesting something other than a regex :P

**Review by JoviDeCroock — APPROVED** [review]
