### PR TITLE
 Fix: TS config file using DefineConfig in a non-type="module" project

### LINKED ISSUE #914: Failed to load wmr.config.ts
**Describe the bug**
`yarn create wmr `  
rename `wmr.config.mjs` to `wmr.config.ts`
then:

```
Error: Failed to load wmr.config.ts
Error [ERR_REQUIRE_ESM]: require() of ES Module .\node_modules\wmr\index.js from .\wmr.config.js not supported.
Instead change the require of index.js in .\wmr.config.js to a dynamic import() which is available in all CommonJS modules.
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of URL

```
**Bug occurs with:**

- [x] `wmr` or `wmr start` (development)
- [x] `wmr build` (production)
- [x] `wmr serve`

**Desktop (please complete the following information):**

- OS: Win 11
- Node Version: 17
- WMR Version: newest

### PR DESCRIPTION
**Pull request by rschristian**
Closes #914

Rather than transpile a `wmr.config.ts` to the default module type of the project, we should instead always transpile it to ESM. No need to touch WMR's exports this way.

### CODE REVIEW

File: packages/wmr/src/lib/compile-single-module.js [hunk 1]
```diff
@@ -74,6 +74,7 @@ export const compileSingleModule = withCache(
 			...ROLLUP_FAST_OUTPUT,
 			dir: out,
 			assetFileNames: '[name].[ext]',
+			...(typeof filename !== 'undefined' && { entryFileNames: filename }),
```
Comment (rschristian) [inline packages/wmr/src/lib/compile-single-module.js:77]: So I attempted to reuse `assetFileNames` here, but for whatever reason, it always created an asset with an extension of `.js`, even if `.mjs` was passed to it. `entryFileNames` seems to handle this though.

I cannot rightly say I understand the difference between the two and the Rollup docs don't really help in that regard. Someone who better understands might want to look at this.

Comment (rschristian) [reply packages/wmr/src/lib/compile-single-module.js:77]: This _seems_ like it should work, and passes the test suite, but I don't understand the difference between the two enough to know for sure whether it's acceptable.

```suggestion
			entryFileNames: filename || '[name].[ext]',
```

Comment (developit) [reply packages/wmr/src/lib/compile-single-module.js:77]: @rschristian that suggestion makes sense - they're doing the same thing really, since `filename` didn't exist before.

**Review by developit — APPROVED** [review]

File: packages/wmr/src/lib/normalize-options.js [hunk 2]
```diff
@@ -106,12 +106,14 @@ export async function normalizeOptions(options, mode, configWatchFiles = []) {
...
-				configFile = resolve(options.cwd, 'wmr.config.js');
+				const tmpConfig = `wmr.config.${pkg && pkg.type === 'module' ? 'js' : 'mjs'}`;
+				configFile = resolve(options.cwd, tmpConfig);
 				await compileSingleModule(file, {
 					out: resolve('.'),
+					filename: tmpConfig,
 					hmr: false,
 					rewriteNodeImports: false,
-					format: pkg && pkg.type === 'module' ? 'es' : 'commonjs'
+					format: 'es'
```
[the remark this answers is not in the document]
Comment (rschristian) [reply packages/wmr/src/lib/normalize-options.js:116]: I'm scared to look at the blame, as I think I remember doing it.

Not sure why I did that, really odd.

[the remark this answers is not in the document]
Comment (developit) [reply packages/wmr/src/lib/normalize-options.js:116]: It's a good find anyway though - I have a feeling this might have been the cause of #647 and related things.

File: packages/wmr/src/lib/compile-single-module.js (hunk 1 above)
Comment (rschristian) [reply packages/wmr/src/lib/compile-single-module.js]: Good to know!

Didn't know if there was enough of a difference between an asset and an entry, even for this tiny, single file use case that would be an issue.
