### PR TITLE
Fix infinite loop when prerendering json imports

### LINKED ISSUE #446: JSON import plugin is broken (infinite loop in production build, blank page in dev mode)
**Describe the bug**

* `npm run build` => shell command hangs forever, and the following addition to `wmr.config.mjs` reveals the infinite loop:

```js
function tracePlugin() {
    return {
        name: 'trace',
        async resolveId(id, _importer) {
            console.log('##### resolveId ', id);
            return undefined;
        },
    };
}
config.plugins.push(tracePlugin);
```

* `npm start` => the page remains blank

**To Reproduce**

1) `npm init wmr json-import`
2) `cd json-import`
3) open `public/pages/_404.js`, add at the top: `import test from './test.json';` or `import test from 'json:./test.json';` (both trigger the bug).
4) add `<pre>{json}</pre>` in the JSX
5) create `test.json` in `public/pages/`, for example (**)
4) `npm run build` or `npm start` + open web browser URL

(**) `test.json`
=>
```json
{
    "key": "value",
    "obj": {
        "array": [1, 2, 3]
    },
    "boolean": false,
    "null": null
}
```

Code culprit (`this.resolve()` seems to call `resolveId()`, recursively):

https://github.com/preactjs/wmr/blob/7e1fb016be6bf91eeaa424a452b1bb215629a52e/packages/wmr/src/plugins/json-plugin.js#L18-L28

**Expected behavior**

The JSON import should work.

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - WMR Version: all

**Additional context**

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This bug was a combination of multiple smaller issues:

- Rollup had an issue with nested resolution calls: https://github.com/rollup/rollup/releases/tag/v2.42.0
- We did add `\0json:` twice to paths during resolution
- We didn't load `\0json:` files properly during prod builds

Fixes #446, fixes #474 .

### CODE REVIEW

**Review by developit — APPROVED** [review]
That was quite the saga, haha.

**Comment by danielweck** [comment]
If I am not mistaken, this PR supersedes https://github.com/preactjs/wmr/pull/458/ ?

File: examples/demo/public/pages/json.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import { useEffect, useState } from 'preact/hooks';
+import json from './foo.json';
+
+export function JSONView() {
+	const [fetched, setFetched] = useState(null);
+
+	useEffect(() => {
+		fetch('./pages/foo.json')
```
Comment (danielweck) [inline examples/demo/public/pages/json.js:8]: Just a thought: this feels like a missed opportunity to demonstrate `import jsonUrl from 'url:./foo.json';` + `fetch(jsonUrl)`. Otherwise, to the reader the relative path `./pages/foo.json` looks like "magic", in the base context of `public/pages/json.js`.
