### PR TITLE
Attempt to fix the router flicker

### LINKED ISSUE #221: Old and new components in DOM on url change with preact-iso Router
There is a very brief flicker in the DOM on url change because of both the old and new route children being rendered at the same time when using the `preact-iso` Router. Here it is magnified with a breakpoint:
old_route_component_in_dom

Is there any way of not having the previous children of the Router being rendered? I don't fully understand the code, but I assume it is this way for the awesome support of lazy components.

### PR DESCRIPTION
**Pull request by cristianbote**
Fixes #221.

Looking to add a test for this.

### CODE REVIEW

File: demo/public/lib/lazy.js [hunk 1]
```diff
@@ -3,14 +3,19 @@ import { useState, useRef } from 'preact/hooks';
...
 export default function lazy(load) {
 	let p, c;
-	return props => {
+	function inner(props) {
 		if (!p) p = load().then(m => ((c = (m && m.default) || m), 1));
 		const [, update] = useState(0);
 		const r = useRef(c);
 		if (!r.current) r.current = p.then(update);
 		if (c === undefined) throw p;
+		inner._r = true;
```
Comment (JoviDeCroock) [inline demo/public/lib/lazy.js:12]: Let's give this a full name rather than `_r` (`_resolved`) and work with mangle (in the future) to better this.

Comment (cristianbote) [reply demo/public/lib/lazy.js:12]: Oh, thank you @JoviDeCroock! Great call. Will change it.

**Review by JoviDeCroock — APPROVED** [review]
Nice work Cristian!

**Comment by cristianbote** [comment]
Based on recent findings I've included an `update(1)` in `componentDidCatch` in order to pickup on the changes. @developit  I think now this is pretty safe for nested thrown promises, cause it does not read any children static property.

Is there any reason why this would lead to bad perf?

Let me know your thoughts.
